### ISSUE TITLE
Error on running example2

### ISSUE THREAD

**Issue by WenLonG12345** [panz3r/react-native-flipper-databases#207]
Hi, I faced issue when running on `example2`. 

Here is the error log

> error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/teowenlong/rn-learning/react-native-flipper-databases/src/databasesFlipperPlugin.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
> If you are sure the module exists, try these steps:
> 1. Clear watchman watches: watchman watch-del-all
> 2. Delete node_modules and run yarn install
> 3. Reset Metro's cache: yarn start --reset-cache
>  4. Remove the cache: rm -rf /tmp/metro-*
> 1 | import type { Flipper } from 'react-native-flipper';
  2 |
  3 | import { DatabasesManager } from './databasesManager';
  4 | import {
    at ModuleResolver.resolveDependency (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Users/teowenlong/rn-learning/react-native-flipper-databases/example2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 1)

Anyone facing this issue? Please help. 
I also implement it into my project and unfortunately the `databases` in flipper said it is unavailable.

**Comment by panz3r** [comment]
Hi,

I cannot reproduce this issue you're facing.
I can only suggest you to try following the steps in the new `Examples` section of the `README` here
[https://github.com/panz3r/react-native-flipper-databases#examples](https://github.com/panz3r/react-native-flipper-databases#examples).

Thanks for your feedback and I hope this can help you.
